---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - libjpeg8-dev
    - python-pip
    - python-psycopg2
    - git

- name: Clone Django Repository
  git: repo=https://github.com/icarrera/django-imager.git dest={{ django_home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml

- name: Change Media Ownership
  sudo: yes
  file: path="{{ django_home }}/imagersite/media/" owner=www-data mode=0755 state=directory

- name: Run Migrations
  environment:
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT : "{{ DB_PORT }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
    IEMAIL: "{{ IEMAIL }}"
    IMAGER_EMAIL_HOST_USER: "{{ IMAGER_EMAIL_HOST_USER }}"
    IMAGER_EMAIL_HOST_PASSWORD: "{{ IMAGER_EMAIL_HOST_PASSWORD }}"
  django_manage:
    app_path: "{{ django_home }}/imagersite"
    settings: imagersite.settings
    command: migrate


- name: Collect Static Files
  environment:
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT : "{{ DB_PORT }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
    IEMAIL: "{{ IEMAIL }}"
    IMAGER_EMAIL_HOST_USER: "{{ IMAGER_EMAIL_HOST_USER }}"
    IMAGER_EMAIL_HOST_PASSWORD: "{{ IMAGER_EMAIL_HOST_PASSWORD }}"
  django_manage:
    app_path: "{{ django_home }}/imagersite"
    settings: imagersite.settings
    command: collectstatic
